version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  sportsbetting:
    container_name: sportsbetting
    image: sportsbetting
    restart: always
    #build: .
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"
    links:
      - mongo
